unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

bind h split-window -hc "#{pane_current_path}"
bind v split-window -vc "#{pane_current_path}"
bind-key C-Space switch-client -l
set -sg escape-time 0
set-option -g status-position top 

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"
bind-key M split-window -h "nvim ~/.tmux.conf"
set-window-option -g mode-keys vi


bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind c new-window -c "#{pane_current_path}"
bind Space last-window
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
